[tools]
aws-cli = "latest"
bat = "latest"
bun = "latest"
claude = "latest"
codex = "latest"
ctop = "latest"
docker-cli = "latest"
docker-compose = "latest"
eza = "latest"
# ffmpeg = "latest"
flyctl = "latest"
git-lfs = "latest"
infisical = "latest"
java = "latest"
mysql = "latest"
neovim = "latest"
ni = "latest"
node = "24.9.0"
pixi = "latest"
pnpm = "latest"
sqlite = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"
yt-dlp = "latest"
zellij = "latest"
