format = """
[](fg:#98971a)\
$username\
[ ](fg:#98971a)\
$custom \
[ ](fg:#3c3836)\
$directory\
[](fg:#3c3836 bg:#504945)\
$git_branch\
$git_status\
[](fg:#504945 bg:#665c54)\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#665c54 bg:#7c6f64)\
$time\
[ ](fg:#7c6f64)\
\n$character
"""

[username]
style_user = "fg:#282828 bg:#98971a"
format = "[$user]($style)"
show_always = true

[hostname]
disabled = false

[directory]
style = "fg:#fbf1c7 bg:#3c3836"
read_only = ''
format = '[ $path ]($style)[$read_only]($style)'
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = true

[custom.hostname]
when = "true"
shell = ["bash"]
command = '''
case "$(hostname)" in
    "shokaku")   COLOR=167 ;;  # gruvbox bright red
    "amagi")     COLOR=142 ;;  # gruvbox bright green
    "hiryu")     COLOR=214 ;;  # gruvbox bright yellow
    "zuikaku")   COLOR=109 ;;  # gruvbox bright blue
    "taiho")     COLOR=208 ;;  # gruvbox bright orange
    "qsoryu")    COLOR=175 ;;  # gruvbox bright purple
    "ryujo")     COLOR=108 ;;  # gruvbox bright aqua
    "hiyou")     COLOR=124 ;;  # gruvbox red
    "maya")      COLOR=100 ;;  # gruvbox green
    "junyo")     COLOR=66  ;;  # gruvbox blue
    "qhiryu")    COLOR=132 ;;  # gruvbox purple
    *)           COLOR=167 ;;  # gruvbox bright red (fallback)
esac

# 色付き、文字本体、
echo -e "\033[38;5;${COLOR}m\033[0m\033[48;5;${COLOR}m\033[38;5;15m@ $(hostname) \033[0m\033[38;5;${COLOR}m\033[0m"
'''
format = "$output"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol $branch ](fg:#d79921 bg:#504945)]($style)'

[git_status]
style = "bg:#504945"
format = '[[($all_status$ahead_behind )](fg:#d79921 bg:#504945)]($style)'

[python]
pyenv_version_name = false
symbol = ""
style = "bg:#665c54"
format = '[ $symbol ($version) ](fg:#ebdbb2 bg:#665c54)[ $virtualenv ](fg:#b8bb26 bg:#665c54)'

[nodejs]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#665c54)]($style)'

[rust]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#665c54)]($style)'

[golang]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#665c54)]($style)'

[php]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol ($version) ](fg:#83a598 bg:#665c54)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#7c6f64"
format = '[[  $time ](fg:#ebdbb2 bg:#7c6f64)]($style)'

[localip]
style = "bg:#83a598"
ssh_only = false
format = '[[ $localipv4 ](fg:#282828 bg:#83a598)]($style)'
disabled = false

